update socket api and user info api
CPG-Innovation-Team/cpg-code-editor-web pull request #18
Opened 2021-08-02 08:13 UTC by fork1028

2021-08-03 07:09 UTC, casualbill commented
PR的内容最好还是填写一下。。。这次试着让Tony/David做下review？
好了我再来看一下

2021-08-05 00:00 UTC, lmy0125 approved these changes
Good work!

2021-08-05 00:00 UTC, lmy0125 commented on src/views/Editor.vue
> +              variables: { hash: this.projectId },
这里难道不是用projectHash吗？这样子感觉有一点迷惑

2021-08-05 02:39 UTC, fork1028 commented on src/views/Editor.vue
> +              variables: { hash: this.projectId },
是的我改一下

2021-08-06 09:58 UTC, casualbill requested changes

2021-08-06 09:58 UTC, casualbill commented on src/views/Editor.vue
> +      this.projectId = this.$route.params.projectHash;
Id = hash... 是不是有点迷惑性。。。

2021-08-09 06:18 UTC, casualbill approved these changes

2021-08-09 06:19 UTC, merged