可拖拽调节界面尺寸，完善project table的create和remove功能
CPG-Innovation-Team/cpg-code-editor-web pull request #19
Opened 2021-08-04 23:39 UTC by lmy0125

将读取所有project数据放到了App.vue中并pass到所有children，
project table的create和remove更改的是App.vue中的project数据，可实时显示结果。

在Editor中加入了自定义调节左边section的大小，在没有initEditor()是可以完美实现，但在initEditor()后有瑕疵，需要改进；
EditorHeader的菜单中可显示并连接到其他projects。

每个project的url使用的是project._id，因为isocket中使用的也是id而非hash。这使得project.code可实现实时同步功能，
可是在使用此功能时此project的projectName和syntax会变的不可被读取从而产生bug。

完善了project.vue部分代码使其更简洁。

2021-08-06 08:48 UTC, casualbill commented on src/views/Editor.vue
> -    this.editor.dispose();
移除 beforeDestroy 是有什么原因吗？

2021-08-06 08:53 UTC, casualbill requested changes

2021-08-06 08:53 UTC, casualbill commented on src/views/Editor.vue
> +  .left {
这边的 class 名最好可以按照语义写全（什么模块的什么内容），也可避免样式污染（虽然这边不会有这个问题）

2021-08-06 08:53 UTC, casualbill commented on src/views/Editor.vue
> +
移除 beforeDestroy 是有什么原因吗？

2021-08-06 08:53 UTC, casualbill commented on src/views/Editor.vue
> +  .middle {
这边的样式名同理。。还有下面的 right

2021-08-06 08:53 UTC, casualbill commented on src/views/Projects.vue
> +                    <router-link :to="item._id" class="project-title">{{ item.projectName }}</router-link>
建议还是使用 hash 来作为路由 URL 链接，hash 的链接更短而且设计 hash 就是为了生成 URL 使用的

2021-08-06 08:53 UTC, casualbill commented on src/views/Projects.vue
> +                    <router-link :to="item._id" class="project-title">{{ item.projectName }}</router-link>
接口可以使用 hash 来查询单个 project 条目

2021-08-06 08:55 UTC, casualbill commented
如果使用 hash 而非 _id 会存在什么问题的话可以讨论，但是设计是使用 hash 来作为项目（唯一）的短链接 URL 使用的

2021-08-10 02:10 UTC, fork1028 commented on src/views/Editor.vue
> +  .left {
我感觉用history-section这种可读性会更好一点

2021-08-11 01:43 UTC, lmy0125 commented
上述问题已解决

2021-08-12 07:21 UTC, casualbill commented
还需要解决一下冲突

2021-08-13 05:10 UTC, lmy0125 commented
删除了有关console的codes和tests

2021-08-13 07:40 UTC, casualbill approved these changes

2021-08-13 07:41 UTC, merged