Feature/history
CPG-Innovation-Team/cpg-code-editor-web pull request #27
Opened 2021-08-30 08:21 UTC by MalusJ

添加左侧和右侧的历史编辑记录功能

2021-08-30 08:42 UTC, casualbill requested changes

2021-08-30 08:42 UTC, casualbill commented on src/components/tools/History.vue
> +        <div class="historyUnit">
注意class命名规则啊亲

2021-08-30 08:42 UTC, casualbill commented on src/components/tools/History.vue
> +      return 'rgb(226, 109, 93)';
这里颜色应该要和用户头像外圈的颜色、光标颜色保持一致。可能需要和 @fork1028 协同一下生成规则

2021-08-30 22:03 UTC, fork1028 commented on src/components/tools/History.vue
> +      return 'rgb(226, 109, 93)';
这个getColor方法我挪到util.js里了之后应该可以直接调用

2021-08-31 04:53 UTC, MalusJ commented on src/components/tools/History.vue
> +        <div class="historyUnit">
好的 已修改

2021-08-31 04:54 UTC, MalusJ commented on src/components/tools/History.vue
> +      return 'rgb(226, 109, 93)';
> 这个getColor方法我挪n到util.js里了之后应该可以直接调用

嗯嗯好的,那我把feature/cursor里的util版本复制进这个要pr的版本了哈。

2021-08-31 04:56 UTC, MalusJ commented on src/components/tools/History.vue
> +      return 'rgb(226, 109, 93)';
> 这里颜色应该要和用户头像外圈的颜色、光标颜色保持一致。可能需要和 @fork1028 协同一下生成规则

嗯，颜色是一致的，获取颜色的代码是直接参考grace的。现在采取的是util里公用的method。

2021-08-31 06:42 UTC, casualbill commented on src/components/tools/History.vue
> +      return 'rgb(226, 109, 93)';
我先合了，有冲突到时候再解决

2021-08-31 06:43 UTC, casualbill approved these changes

2021-08-31 06:43 UTC, casualbill commented
还有冲突需要解决下

2021-09-01 03:42 UTC, merged