Feature cursor: add basic logic
CPG-Innovation-Team/cpg-code-editor-web pull request #28
Opened 2021-08-31 18:22 UTC by fork1028

* 用户输入时在光标处显示‘正在输入中’
* 输入完毕后在所有project页面更新用户光标
* 当前用户光标颜色和用户头像边框颜色保持一致

2021-09-01 03:40 UTC, casualbill requested changes
另外现在开始 feature 分支的PR先合 staging

2021-09-01 03:40 UTC, casualbill commented on src/util.js
> +  return '#E26D5D';
这种情况感觉 switch/case 比 if/else 可读性会好些，
而且这里写一个对应键值对的 map 可能会更好（可以在map.js里）

2021-09-01 21:09 UTC, fork1028 commented on src/util.js
> +  return '#E26D5D';
先改成了switch statement，我想想map要怎么改

2021-09-02 02:23 UTC, casualbill approved these changes

2021-09-02 05:47 UTC, merged